name: ColorCode
version: '1.0'
main: ict.minesunshineone.color.ColorCode
api-version: '1.21'
description: A plugin that allows players to use color codes on signs and anvils
author: MineSunshineone
folia-supported: true
permissions:
  colorcode.sign:
    description: Allows using color codes on signs
    default: op
  colorcode.anvil:
    description: Allows using color codes in anvils
    default: op
  colorcode.chat:
    description: Allows using item display in chat
    default: true 