name: SimpleChat
version: '${project.version}'
main: ict.minesunshineone.chat.SimpleChat
api-version: '1.20'
description: 一个简单但功能丰富的 Minecraft 聊天管理插件
author: MineSunshineone
folia-supported: true
softdepend: ["PlaceholderAPI"]

# 权限节点配置
permissions:
  simplechat.chat.color:
    description: 允许在聊天中使用颜色代码
    default: op
  simplechat.chat.mentionall:
    description: 允许在聊天中使用@all功能
    default: op
  simplechat.sign.color:
    description: 允许在告示牌上使用颜色代码
    default: op
  simplechat.anvil.color:
    description: 允许在铁砧上使用颜色代码
    default: op
  simplechat.mute:
    description: 允许使用禁言和解除禁言命令
    default: op
  simplechat.admin.reload:
    description: 允许重载插件配置
    default: op

commands:
  mute:
    description: 禁言玩家
    usage: /mute <玩家> <时长> <原因>
    permission: simplechat.mute
  unmute:
    description: 解除玩家禁言
    usage: /unmute <玩家>
    permission: simplechat.mute
  chatreload:
    description: 重载SimpleChat插件配置
    usage: /chatreload
    permission: simplechat.admin.reload 