name: ColorCode
version: '1.4'
main: ict.minesunshineone.color.ColorCode
api-version: '1.21'
description: 一个允许玩家在告示牌和铁砧上使用颜色代码的插件
author: MineSunshineone
folia-supported: true
softdepend: ["PlaceholderAPI"]

# 权限节点配置
permissions:
  colorcode.sign.color:
    description: 允许在告示牌上使用颜色代码
    default: op  # 默认仅管理员可用
  colorcode.anvil.color:
    description: 允许在铁砧上使用颜色代码
    default: op  # 默认仅管理员可用
  colorcode.chat.color:
    description: 允许在聊天中使用颜色代码
    default: op  # 默认仅管理员可用
  colorcode.chat.mentionall:
    description: 允许在聊天中使用@all功能
    default: op  # 默认仅管理员可用 