name: ColorCode
version: '1.0'
main: ict.minesunshineone.color.ColorCode
api-version: '1.21'
description: 一个允许玩家在告示牌和铁砧上使用颜色代码的插件
author: MineSunshineone
folia-supported: true

# 权限节点配置
permissions:
  colorcode.sign:
    description: 允许在告示牌上使用颜色代码
    default: op  # 默认仅管理员可用
  colorcode.anvil:
    description: 允许在铁砧上使用颜色代码
    default: op  # 默认仅管理员可用
  colorcode.chat:
    description: 允许在聊天中展示物品
    default: true  # 默认所有玩家可用 